---
# from https://github.com/jalefkowit/Vagrant-Ansible-Wordpress
- hosts: vagrant
  remote_user: vagrant
  sudo: yes
  vars_files:
    - sites.yml
  tasks:
    - name: Install base packages
      apt: pkg={{ item }} state=latest
      with_items:
        - curl
        - fail2ban
        - git
        - python-software-properties
        - rsync
        - ufw
        - unattended-upgrades
        - unzip
        - vim-tiny

    - name: Install PHP and modules
      apt: pkg={{ item }} state=latest
      with_items:
        - php5
        - php-apc
        - php-pear
        - php5-cli
        - php5-curl
        - php5-gd
        - php5-imagick
        - php5-mcrypt
        - php5-memcache
        - php5-mysql
        - php5-xmlrpc
      tags:
        - php

    - name: Install Apache
      apt: pkg={{ item }} state=latest
      with_items:
        - apache2
        - libapache2-mod-php5
      tags:
        - apache

    - name: Enable Apache modules
      apache2_module: name={{ item }} state=present
      with_items:
        - deflate
        - expires
        - mime
        - rewrite
        - setenvif
        - ssl
      tags:
        - apache

    - name: Install MySQL
      apt: pkg={{ item }} state=latest
      with_items:
        - mysql-client
        - mysql-server
        - python-mysqldb
      tags:
        - mysql

    - name: Start MySQL service
      service:
        name: mysql
        state: started
        enabled: yes

    - name: Setup MySQL root password
      mysql_user:
        name: "root"
        password: "mysql"
        host: "{{ item }}"
        state: present
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Setup MySQL creds for root user
      template:
        src: "{{ mysqlTemplatePath }}"
        dest: "/root/.my.cnf"
        owner: "root"
        mode: 0600

    - name: Setup MySQL creds for vagrant user
      template:
        src: "{{ mysqlTemplatePath }}"
        dest: "/home/vagrant/.my.cnf"
        owner: "root"
        mode: 0600

    - name: Delete blank MySQL users
      mysql_user:
        name: ""
        host: "{{ item }}"
        state: absent
      with_items:
        - "{{ ansible_hostname }}"
        - 127.0.0.1
        - ::1
        - localhost

    - name: Drop MySQL test database
      mysql_db: name=test state=absent


    - name: Add groups
      group:
        name: "{{ item.value.user }}"
        state: present
      with_dict: sites
      tags:
        - sites

    - name: Add users
      user:
        name: "{{ item.value.user }}"
        group: "{{ item.value.user }}"
        groups: "www-data"
        shell: /bin/bash
        state: present
      with_dict: sites
      tags:
        - sites

    - name: create authorized_keys
      authorized_key:
        key: "{{ lookup('file', 'authorized_keys') }}"
        user: "{{ item.value.user }}"
        state: present
      with_dict: sites
      tags:
        - sites

    - name: Add user hosting paths
      file:
        state: directory
        path: "{{ item.value.htroot }}"
        recurse: yes
        mode: 0755
        owner: "{{ item.value.user }}"
        group: "{{ item.value.user }}"
      with_dict: sites
      tags:
        - sites

    - name: Deactivate default vhost
      command: a2dissite 000-default
      tags:
        - apache

    - name: Ensure Apache is running
      service: name=apache2 state=restarted enabled=yes
      tags:
        - apache

    - name: Enable UWF
      ufw: state=enabled policy=reject logging=on
      tags:
        - firewall

    - name: Open TCP ports
      ufw: rule=allow port={{ item }}
      with_items:
        - 20
        - 22
        - 25
        - 443
        - 587
        - 80
        - 993
      tags:
        - firewall

    - name: Ensure UFW running
      service:
        name: ufw
        state: started

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted
